### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by gnoxr**
The database engine has been externalized, now it should be easy to switch the DB if it is needed.
The Mongo code has been greatly simplified (thanks to a "getCollection" function).
All CRUDS routes have been tested, except the "import" and "file" ones. The dam.js and the upload.js routes were not tested for now.

The API is fully compatible with the precedent one, including only a new feature : we can create() multiple nodes at once by providing an array of nodes.

There is also a "debug" database engine implemented with a minimal set of functions, which can be used to for debugging purposes as it does not handle data. It also shows how to implement another database engine and how to link it to the working system (via lib/database.js).

### CODE REVIEW

**Comment by gnoxr** [comment]
The last commits include the following changes :

- Recovered history of `model.js` (use `git log --follow` to see them, as the file was renamed)
- `prepare_regexes()` function is now inside the routes/
- `README.md` updated following the changes in the configuration file
- Database engines moved to the `db/` directory (with `db/index.js` being the Factory)

**Comment by remyla** [comment]
mongodb driver, mongodb.js:
* the data model methods should not change the input parameters types
* we can accept only arrays here
* changing the types of the elements (strings changed to ObjectIds) in the input array passed as reference is something a bit dangerous as this could lead to problems in the calling context

**Comment by gnoxr** [comment]
These problem should have been solved in the last commit.

**Comment by remyla** [comment]
thank you very much.
I merged this pull request with the experimental branch

**Pull request closed without merging**
