### PR TITLE
Basic CRUD for the nodeJS/MongoDB server

### PR DESCRIPTION
**Pull request by Baenshee**
The basic CRUD for the nodeJS/MongoDB server is working.
The server listens to the ports 8090(due to local conflicts) and 443. It can be changed in the file server-nodejs/conf.json.

### CODE REVIEW

**Comment by remyla** [comment]
Thank you very much. However I request some changes in order to pull the changes:

regarding the pull request itself:

* /server-nodejs/node_modules should not be tracked
* the certificate keys for https should not be in this repository, these file are server-specific. Having a hard-coded certificate in a public repository is a security issue

regarding the code:

* model.js should not handle the http results. This is the job for routes.js. The methods in model.js should should accept a callback function as parameter (the asynchrone scheme is preferred)
* route.js should be renamed routes.js
* package.json should reflect the changes of renaming the server.js file

**Comment by Baenshee** [comment]
Key and node_modules untracked.
Code updated.

**Comment by remyla** [comment]
Thanks, here are the problems I see in model.js

* the errors returned by mongo.Db.collection() should always be processed. It is not processed except for the read method but it calls the callback with the error string instead of the error itself
* the create method is missing a callback parameter for the callback function
* the update method: create 2 arrays from keys: one with keys to set, one with keys to remove. Call collection.update with $set on first array then $unset on second array
* the collection.remove() method is deprecated
* this file should not run the server (leave it like that for now, we will discuss about it later)

**Comment by remyla** [comment]
Now some directions for routes.js:

* the input parameters should be checked for these CRUD operations.  An HTTP error is returned (400) if the required parameters are missing (Bad Request). Please carefully read the PHP implementation, which takes care of theses checks, and returns the errors: https://github.com/remyla/damas-core/blob/master/server-php/model.json.php
* the create operation is returning keys._id from the keys input parameter (which however may not exist) - in our specifications, the created object is returned, in JSON format (see model.json.php)

**Comment by Baenshee** [comment]
Code updated to take these comments into account.

**Comment by remyla** [comment]
model.js

* error handling is different from functions to functions. Sometimes the callback is called with err. Sometimes with a 'err'+string. Sometimes there is a log message but not always. Please provide a simple, clean, easy to read way to handle errors. Please have a look at this example:
<pre>
CollectionDriver.prototype.getCollection = function(collectionName, callback) {
    this.db.collection(collectionName, function(error, the_collection) {
        if( error ) callback(error);
        else callback(null, the_collection);
    });
};
</pre>

then, a delete methods which uses it:
<pre>
CollectionDriver.prototype.delete = function(collectionName, entityId, callback) {
    this.getCollection(collectionName, function(error, the_collection) { //A
        if (error) callback(error);
        else {
            the_collection.remove({'_id':ObjectID(entityId)}, function(error,doc) { //B
                if (error) callback(error);
                else callback(null, doc);
            });
        }
    });
};
</pre>

* update method - please rewrite this method:
    * The use of the Array type is quite obvious here (https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array) to handle lists of keys.
    * the safe:true is not part of the documented available options. http://mongodb.github.io/node-mongodb-native/2.0/api/Collection.html#updateOne.

Please take more care of what you write in general, following the documentations, else I need to review everything and I can't trust what is written

**Pull request merged**
