### PR TITLE
Upgraded search

### PR DESCRIPTION
**Pull request by Baenshee**
This new version can search with comparison operators (>,>=,<,<=) and manages unneeded spaces.

### CODE REVIEW

**Comment by remyla** [comment]
here is my review on your code in route.js

* the comparison indexOf(operator) > 0 should be === 0 (you try to figure out if the string starts with an operator, not having an operator in it anywhere)
* the String.split() method is not very adapted here.. you want to remove the operator from the string, String.replace(Regexp,'') could work in a more adapted manner, and will not fail if the operator character is found many times
* again, the use of many many nested if else (and with the same evaluated condition (temp.length===1) should alert the writer that the way to write it could be more elegant somehow. Here, you could give a try to the "continue" statement https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Instructions/continue

thanks

**Comment by remyla** [comment]
following the specifications, the search operator should return an array of indexes

**Comment by Baenshee** [comment]
-In the example research query "time<12345678", the operator will not necessarily be the first character in the split string, hence the > operator.
-I'm not trying to remove the operators from the string, just to take the string apart to use it to create the object which will be sent to the search method.
-These return values were for testing purpose only. It has already been changed.

**Comment by remyla** [comment]
thank you

**Comment by remyla** [comment]
the search operator is not returning arrays of indexes

**Pull request merged**
